### ISSUE TITLE
Implement HM-10 driver, Bluetooth 4.0 Serial Port Module based on CC2541 MCU

### ISSUE THREAD

**Issue by forGGe** [forGGe/theCore#203]
[HM-10 module](https://goo.gl/4qBvgh) is cheap device that provides BLE connectivity via serial port.
Driver must be implemented for that.

Some useful links:
 - [Instructables tutorial](http://www.instructables.com/id/How-to-Use-Bluetooth-40-HM10/)
 - [Spec](http://www.pridopia.co.uk/pi-doc/BT4.0-HM-10-Serial_Port_BLE_Module_Master_Slave.pdf)
 - [Sunfounder guide](https://www.sunfounder.com/wiki/index.php?title=Bluetooth_4.0_HM-10_Master_Slave_Module)

Requires:

- [x] - #210 Xfer timeout and/or #207 - to not get stuck if HC10 module is not responding
- [x] - #208 Control completion of xfer - to set expectancy of incoming data message size.
- [x] - #231 Terminate event would help to avoid infinite waiting during blocking xfer

**Comment by forGGe** [comment]
Implemented and tested in #235
