### ISSUE TITLE
Implement MFRC522 driver

### ISSUE THREAD

**Issue by forGGe** [forGGe/theCore#37]
The MFRC522 is a highly integrated reader/writer IC for contactless communication at 13.56 MHz. It can be found in a cheap RFID reader/writer modules like [this](http://www.ebay.com/itm/MFRC-522-RC522-RFID-Radiofrequency-IC-Card-Inducing-Sensor-Reader-for-Arduino-BE-/191371999374?hash=item2c8ea8f88e:g:igAAAOxyBjBTRMCs).

UART is preferable as communication mode between MCU and MFRC522.
**Unit tests required.** 

Additional implementation inside existing code is also required:
 - [ ] #34 Configurable USART modes are required to support different baud rates.
 - [ ] #35 EXTI driver will supply the Core with interrupts from MFRC522
 - [ ] #36 FIFO read/write can be triggered while servicing EXTI IRQ. This will decrease response latency significantly.

Refs:
[Datasheet.](http://www.nxp.com/documents/data_sheet/MFRC522.pdf)
